### ISSUE TITLE
Tracking Issue: complete N-API

### ISSUE THREAD

**Issue by sehz** [infinyon/node-bindgen#96]
Following N-API wrapper need to be created for `JsEnv`:

- [ ] napi_create_arraybuffer
- [ ] napi_create_buffer
- [ ] napi_create_buffer_copy
- [ ] napi_create_date
- [ ] napi_create_external
- [ ] napi_create_external_arraybuffer
- [ ] napi_create_external_buffer
- [ ] napi_create_symbol
- [ ] napi_create_typedarray
- [ ] napi_create_dataview
- [ ] napi_create_uint32
- [ ] napi_create_bigint_int64
- [ ] napi_create_bigint_uint64
- [ ] napi_create_bigint_words
- [ ] napi_create_string_latin1
- [ ] napi_get_array_length
- [ ] napi_get_arraybuffer_info
- [ ] napi_get_buffer_info
- [ ] napi_get_prototype
- [ ] napi_get_typedarray_info
- [ ] napi_get_dataview_info
- [ ] napi_get_value_bool
- [ ] napi_get_value_double
- [ ] napi_get_value_bigint_int64
- [ ] napi_get_value_bigint_uint64
- [ ] napi_get_value_bigint_words
- [ ] napi_get_value_external
- [ ] napi_get_value_int32
- [ ] napi_get_value_int64
- [ ] napi_get_value_string_utf8
- [ ] napi_get_value_uint32
- [ ] napi_get_null
- [ ] napi_coerce_to_bool
- [ ] napi_coerce_to_number
- [ ] napi_coerce_to_string
- [ ] napi_instanceof
- [ ] napi_is_dataview
- [ ] napi_strict_equals
- [ ] napi_detach_arraybuffer
- [ ] napi_is_detached_arraybuffer
- [ ] napi_get_property_names
- [ ] napi_get_all_property_names
- [ ] napi_delete_property
- [ ] napi_set_named_property
- [ ] napi_get_named_property
- [ ] napi_has_named_property
- [ ] napi_has_element
- [ ] napi_delete_element
- [ ] napi_create_function
- [ ] napi_get_version
- [ ] napi_get_uv_event_loop
